# Ajusta `to` con el dominio real del backend publicado en Render.

[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://backend-ejemplo.onrender.com/api/:splat"
  status = 200
  force = true
