spring:
  datasource:
    url: jdbc:h2:mem:litethinking;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

server:
  port: ${PORT:8080}
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET:default-jwt-secret-key-please-change}
  expiration-minutes: 60

aws:
  region: ${AWS_REGION:us-east-1}
  ses:
    sender: ${AWS_SES_SENDER:no-reply@litethinking.com}
    enabled: ${AWS_SES_ENABLED:false}
  s3:
    bucket: ${AWS_S3_BUCKET:litethinking-inventory}
    enabled: ${AWS_S3_ENABLED:false}

mail:
  provider: ${MAIL_PROVIDER:local}
  sender: ${MAIL_SENDER:no-reply@litethinking.com}
  sendgrid:
    api-key: ${SENDGRID_API_KEY:}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
